### ISSUE TITLE
Missing Gen 8 Ranked Battle Series 4 & 5 Rules

### ISSUE THREAD

**Issue by foohyfooh** [projectpokemon/EventsGallery#116]

**Comment by kamronbatman** [comment]
@PP-theSLAYER, or @SciresM Do you have these?

**Comment by kamronbatman** [comment]
For anyone that is wondering how we get these, it is pretty straight forward. Boot into emunand and extract the BCAT data. There should be tools online by now to do this. Eventually Checkpoint should have this as a feature too.

**Comment by foohyfooh** [comment]
Checking if anything is being done to resolve this or #127 ?

**Comment by kamronbatman** [comment]
I don't think we have the data. I'll have to check with @SciresM

**Comment by InternalLoss** [comment]
Single and Double for Series 4 & 5 show in my save as "NEW" - would it be useful for me to dump my BCAT data?

**Comment by kamronbatman** [comment]
Yes it would!

**Comment by PP-theSLAYER** [comment]
Slight correction: Rules are not in the BCAT.
They have to be extracted from the saves, after the save is updated with the Rules.

In any case, feel free to visit here: https://github.com/projectpokemon/rules-repo
EventGallery would no longer hold on to the Rules
