### ISSUE TITLE
Missing Late Gen 7 WonderCards - LGPE & USUM

### ISSUE THREAD

**Issue by MarsWonderBoy** [projectpokemon/EventsGallery#117]
Essentially all of LGPE and some events from USUM after the August 2018 date.
They're present in the Event Gallery page on PP, but missing from Pkhex mgdb archive here.

**Comment by kamronbatman** [comment]
I havent made an mgdb release in a while. I'll do that today.
Meanwhile you can download the entire repository, rename Released to mgdb, and use that.

**Comment by kamronbatman** [comment]
https://github.com/projectpokemon/EventsGallery/releases/tag/v2020-07-25
