### ISSUE TITLE
Korea Charizard Distribution data is here

### ISSUE THREAD

**Issue by iant632** [projectpokemon/EventsGallery#124]
[https://drive.google.com/file/d/1OcyNXXQAqX6qXuxxBWSq8ziO_PzjbtXu/view?usp=sharing](url)

I extracted it directly from BCAT. This distribution will start at 30, September in Korea so you may upload it in correct time.

Thanks a lot!

**Comment by kamronbatman** [comment]
Thank you!! I really appreciate as many people extracting bcat as possible. For this one someone submitted it and it is in the Unreleased section.

Keep it up, you never know what test cards or changes may come! Thanks again!
