### ISSUE TITLE
Official Competition Data and Rules Missing:

### ISSUE THREAD

**Issue by Manu098vm** [projectpokemon/EventsGallery#127]
2020 International Challange April - Rules
Date
March 26th - April 12th

2020 International Challenge February
Date
February 19th - March 1st

2020 International Challange May - Data & Rules
Date
May 14th - May 24th

Armor Beginnings - Data & Rules
Date
July 16th- July 26th

International Friendly - Armor & Rules
Date
June 11th - June 28th

PJCS 2020 - Data & Rules
Date
June 11th - June 28th

GCA - Players Cup II - Data & Rules
Date
September 10th - September 27th

Series 4 Singles/Doubles - Rules

Series 5 Singles/Doubles - Rules

Series 6 Singles/Doubles - Rules

Series 7 Singles/Doubles - Rules

Series 8 Singles/Doubles - Rules

Series 9 Singles/Doubles - Rules

**Comment by PP-theSLAYER** [comment]
In any case, feel free to visit here: https://github.com/projectpokemon/rules-repo
EventGallery would no longer hold on to the Rules
