### ISSUE TITLE
BCAT dump from Sword - somewhat unknown contents

### ISSUE THREAD

**Issue by InternalLoss** [projectpokemon/EventsGallery#173]
I'm not exactly sure of everything inside here, but I think I got some of the old rules that are apparently missing - if I didn't then I apologise :p

Dumped today from my EUR copy of Sword with JKSV:
[sword.zip](https://github.com/projectpokemon/EventsGallery/files/6050980/sword.zip)

**Comment by kamronbatman** [comment]
Thanks!!

**Comment by InternalLoss** [comment]
No problem! Hope it's helpful :D

**Comment by PP-theSLAYER** [comment]
Thanks for the contribution. However rules are not in the BCAT.

In any case, feel free to visit here: https://github.com/projectpokemon/rules-repo
EventGallery would no longer hold on to the Rules
