### ISSUE TITLE
Issues with Party of the Decade and Journey Across America

### ISSUE THREAD

**Issue by Bl4ckSh4rk** [projectpokemon/EventsGallery#245]
There are a few issues with the following files:

- [RSEFL - 10 ANIV Fly Pikachu (84D6) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Party%20of%20the%20Decade/RSEFL%20-%2010%20ANIV%20Fly%20Pikachu%20(84D6)%20(ENG).pk3) The checksum is broken, it doesn't even load correctly in PKHeX.
- [RSEFL - 10 ANIV Alakazam (CEB4) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Party%20of%20the%20Decade/RSEFL%20-%2010%20ANIV%20Alakazam%20(CEB4)%20(ENG).pk3) and [RSEFL - 10 ANIV Alakazam (17A7) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Journey%20Across%20America/Top%2020/RSEFL%20-%2010%20ANIV%20Alakazam%20(17A7)%20(ENG).pk3) Ability doesn't match the PID, should have Inner Focus, not Synchronize.
- [RSEFL - 10 ANIV Blastoise (9766) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Party%20of%20the%20Decade/RSEFL%20-%2010%20ANIV%20Blastoise%20(9766)%20(ENG).pk3) Protect's PP are 25 which is way beyond the legally possible maximum of 16.
- [RSEFL - 10 ANIV Umbreon (0372) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Party%20of%20the%20Decade/RSEFL%20-%2010%20ANIV%20Umbreon%20(0372)%20(ENG).pk3) and [RSEFL - 10 ANIV Umbreon (90D6) (ENG).pk3](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%203/ENG/10th%20Anniversary%20Celebration/Journey%20Across%20America/Top%2020/RSEFL%20-%2010%20ANIV%20Umbreon%20(90D6)%20(ENG).pk3) Both have a marking applied.

**Comment by kamronbatman** [comment]
Thanks! I'll remove them and look for replacements in my collection.
