### ISSUE TITLE
Unknown Pokémon Legends: Arceus files downloaded via BCAT

### ISSUE THREAD

**Issue by InternalLoss** [projectpokemon/EventsGallery#251]
The following files were downloaded via BCAT on my Switch while monitoring, and placed into folder `08`:
[UnkFiles.zip](https://github.com/projectpokemon/EventsGallery/files/8116633/UnkFiles.zip)

As this place usually houses event files and these were downloaded in the same way, I'd like to ask if you have any clue on what they're meant to be ^^

**Comment by kamronbatman** [comment]
We will take a look! Thanks! @PP-theSLAYER

**Comment by kwsch** [comment]
Closed by https://github.com/projectpokemon/EventsGallery/pull/254

**Comment by kamronbatman** [comment]
Thanks!
