### ISSUE TITLE
Walking Wake and Iron Leaves Spotlight With Inteleon the Unrivaled Raid Files

### ISSUE THREAD

**Issue by foohyfooh** [projectpokemon/EventsGallery#348]
The current raid which has both Walking Wake and Iron Leaves Spotlight and Inteleon the Unrivaled is missing.

**Comment by Manu098vm** [comment]
Added in https://github.com/projectpokemon/EventsGallery/commit/92213bd3f89cd9bbf680b6ddca2e6d6691557a8d
