### ISSUE TITLE
XYORAS ポケセン Pumpkaboo has an issue.

### ISSUE THREAD

**Issue by ScarlettHaze** [projectpokemon/EventsGallery#357]
They are listed as Male and Female versions of the wondercard yet they are both Female, there is no Male version its just a duplicate of the female version.

0122 XYORAS - ポケセン Pumpkaboo (JPN) (M).wc6
0122 XYORAS - ポケセン Pumpkaboo (JPN) (F).wc6

**Comment by ScarlettHaze** [comment]
[0122 XYORAS - ポケセン Pumpkaboo (JPN) (M).wc6.zip](https://github.com/projectpokemon/EventsGallery/files/11638632/0122.XYORAS.-.Pumpkaboo.JPN.M.wc6.zip)
Here is a version that is Male that I received a while ago from someone.

**Comment by kamronbatman** [comment]
Thanks! @PP-theSLAYER can you verify and do a PR? I am not near a computer.
