### ISSUE TITLE
QR Codes

### ISSUE THREAD

**Issue by kamronbatman** [projectpokemon/EventsGallery#40]
@Bl4ckSh4rk 
I am not sure how easy it would be, but I like the QR codes you uploaded which were 0.5KB.  The Alolan Dex ones are 100x the size.

Also we do not have the Ga'ore shiny QRs from https://projectpokemon.org/home/gallery/album/821-jp-ga-ore-shinies/ - Of which I am not sure if our album is complete either?

Let me know your thoughts!

**Comment by Bl4ckSh4rk** [comment]
I used [Irfanview](http://www.irfanview.com/) with the Riot plugin to reduce the file sizes of the QR codes.
Photoshop should be able to reduce the size as well but unfortunately not as much as Irfanview can, but almost. Though it can batch edit images, I did that a few years ago to resize images. Maybe I can figure that out again and reduce the Alolan Dex QRs a bit at least. PS should be able to reduce the file sizes to 20-25% of what they are now I guess. Without the sprite in the middle and the text below we could reduce it even more... but 20-25% is better than nothing.

**Comment by kamronbatman** [comment]
@Bl4ckSh4rk - Thank you for doing this!

Do you think it is worth it to remove the text/sprite? It seems like quite a bit of work!

**Comment by Bl4ckSh4rk** [comment]
If we remove the sprites and texts we could reduce the sizes even more maybe even to the size of the Magearna/Pikachu codes.
With Photoshop it should be relatively easy to do.

**Comment by kamronbatman** [comment]
Thank you for help with this! I am closing this issue.
