### ISSUE TITLE
missing? 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [projectpokemon/EventsGallery#426]
https://bulbapedia.bulbagarden.net/wiki/List_of_PCNY_event_Pok%C3%A9mon_distributions_(Generation_II)#Shiny_Articuno

Shiny Articuno, Shiny Zapdos, Shiny Moltres I'm assuming these are sadly still missing

**Comment by kamronbatman** [comment]
Yeah, most are lost.

**Comment by kamronbatman** [comment]
Damn!
