### ISSUE TITLE
Possible issue with wc4?

### ISSUE THREAD

**Issue by Ammako** [projectpokemon/EventsGallery#43]
Only tried Battle Series 2009 Arcanine, might need investigating with other Korean wc4 (or other languages.)

Loading the .wc4 in PKHeX, the Wondercard displays fine in PCD slot, but the gift from PGT slot results in a Bad Egg in-game every time.
If I instead use the .pcd from the [PCD archive](https://github.com/projectpokemon/EventsGallery/blob/master/Extras/PCDs.zip), it works fine.

Issue with how the wc4 files were made? Or issue on PKHeX's end with handling wc4?

**Comment by kamronbatman** [comment]
Thanks, I'll look into it.  The files with a (P) were PGTs that I created PCDs from.  I kept the PCDs for this exactly reason, so we can compare and fix any issues.

**Comment by Ammako** [comment]
Game displays it as bad egg, PKHeX shows a red slot. Both indicating corrupted/invalid data.

**Comment by kamronbatman** [comment]
@Ammako - I tested this on the newest master for PKHex and could not replicate the issue with the existing WC4. Can you verify that you are using the newest version and test again?

I also verified and the WC4 is accurate.  I tested by exporting the PKM from the PCD via mystery gift editor and verified that against the contents in the WC4.

**Comment by Ammako** [comment]
Newest master, yes.

Step-by-step of what I do:
1. Download files for latest master of PKHeX, compile Release using Visual Studio 2017;
2. Navigate to [the Wondercard](https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%204/Wondercards/KOR/011%20DP%20-%20%EB%B0%B0%ED%8B%80%EC%8B%9C%EB%A6%AC%EC%A6%88%20Arcanine%20(KOR)%20(P).wc4) in this repo's file, download by hitting Download button, file md5 49C3127BC4D0F47781B24AE3D201CD2B;
3. Open Diamond save file in PKHeX, straight to Mystery Gift menu, import by clicking Import and selecting the file. Right-click Set on PCD slot 1 and PGT slot 1.
4. Hit Save, and save the file.

After that, I'm getting a bad egg from the delivery guy. Happened when using a fresh Korean save file on a flashcart, but the same is happening on an English rom with a save file downloaded off the internet, running on emulator for testing purposes.

- Should I be compiling Debug for non-stable commits like this?
- Is the file somehow getting corrupted during download? This is my third time downloading it and it's been that way every time.
- Could it be that it works fine in Platinum/HG/SS, but not in Diamond/Pearl? I can probably test that out, tbh. and since I'm already testing I might as well try other wc4s.

**Comment by kamronbatman** [comment]
Your MD5 is correct.  I tested with Diamond and Platinum and I cannot reproduce the problem.  I do not have a red slot (corrupted data).  When I import, I see the arcanine, and then I press SHIFT to set and it works.  Drag/Drop works too.

**Comment by Ammako** [comment]
It's weird. I tried with the latest stable release, bad eggs consistently when importing wc4.

Regardless, it doesn't seem like the issue lies with the files on here. I'd still like to figure out why it consistently does not work for me, though.

(If it interests you, still, I could start a new fresh save file and see if it happens there still, and attach it here to see if you are able to replicate the issue using that save file as opposed to yours.)

**Comment by kamronbatman** [comment]
Yeah I am definitely interested in more testing.  It does seem like it is a potential issue with PKHex.  feel free to grab me on Discord and I can send you my PKHex version for further testing too.

**Comment by Ammako** [comment]
Yeah. Retail Diamond on my 3DS, just in case flashcart was doing something weird to the save file. Backing up and restoring using TWLSaveTool 1.2.
It happens there too. Ruled out the possibility of it being flashcart or emulator error, but that only makes it even weirder.

I'm smart and forgot to keep a copy of the save pre-injecting the Wondercard, but maybe you can see something in those regardless (failing that you'd be able to reproduce the issue by importing wc4 in that save file, at least.)

[TWLSaveTool.zip](https://github.com/projectpokemon/EventsGallery/files/1730019/TWLSaveTool.zip)

**Comment by kamronbatman** [comment]
@Ammako - Here is the import (drag/drop) to your D0 file.
<img width="515" alt="screen shot 2018-02-15 at 6 13 40 pm" src="https://user-images.githubusercontent.com/3953314/36290788-09dcd2f6-127c-11e8-86de-8e56e575e5a3.png">

**Comment by Ammako** [comment]
No I know, it imports and everything displays fine in PKHeX Mystery Gift window. It's once I receive it in-game that it gives me a bad egg (likewise, PMGE yells at me a lot about invalid data in my gift slots, lol. Yet PKHeX sees everything fine where PMGE sees corruption.)

**Comment by Ammako** [comment]
(As a side-effect, I can't properly delete/clear the PCD slot unless I save a .pcd to it first to overwrite the bad data.)

**Comment by kamronbatman** [comment]
PGME cannot load WC4 files.  Does it complain about the PCD?

**Comment by Ammako** [comment]
I am loading the save files, not the cards.

Save file with wc4 loaded into them by PKHeX, PMGE complains about invalid characters and show corruption in the Pokémon slot, and a save file with pcd loaded is A-OK.

**Comment by kamronbatman** [comment]
I'll dive into this more when I get time, but if I had to guess, PKHex is not encrypting the PKM when it saves the PGT portion.
