### ISSUE TITLE
Some WC6Full files not importing into PKHex.

### ISSUE THREAD

**Issue by crzyc** [projectpokemon/EventsGallery#53]
See title. Mons like Happy Meowth and Satay King Pikachu are just some mons that have this issue. The Skytree Rayquaza mentioned previously also have this problem, which is the reason why I initially thought that it was not in the database. I'm not sure if this is a PKHex issue or an MGDB issue, so I just posted it here.

Edit: Never mind, this is a PKHex issue. Closed.

**Comment by kamronbatman** [comment]
If PKHex has an issue importing the pokemon then it could mean one of two problems:
- I had a bug in my program for PCD->WC4. This can be tested by checking the hex data manually, and dropping the WC4 and testing generation.
- PKHex has a bug and is doing something wrong in the import process. This definitely was the case for older versions of PKHex.
