### ISSUE TITLE
e-card japanese dolls

### ISSUE THREAD

**Issue by fabiojc99** [projectpokemon/EventsGallery#54]
Hi! I have been looking at this file for some time now and noticed that the e-card japanese Regis dolls  are missing!

**Comment by kamronbatman** [comment]
@fabiojc99, unlike trainers/berries, other cards like decorations were not stored in the save file directly. This means we would need to store the RAW file (which I intend to upload later), but you would not be able to simply inject with an app. You will have to redeem it yourself using VBA+Ereader

**Comment by fabiojc99** [comment]
I knew that already, I was just wondering why the RAW wasn't uploaded.
Thanks for the reply!

**Comment by PP-theSLAYER** [comment]
I've uploaded a bunch of .RAWs, so at least the e-card for the Japanese dolls is now resolved :)
