### ISSUE TITLE
Gen III JEREMY

### ISSUE THREAD

**Issue by fabiojc99** [projectpokemon/EventsGallery#76]
Hi! I think I saw that there were some JEREMY Pokemon in ProjectPokemon but there aren't any here...

**Comment by kamronbatman** [comment]
The ones we have are here: https://github.com/projectpokemon/EventsGallery/tree/master/Released/Gen%204/Palparked%20from%20Gen%203/USA/JEREMY

**Comment by fabiojc99** [comment]
But there is a save in ProjectPokemon with some Jeremy Pokemon still in gen III.
https://projectpokemon.org/home/files/file/3277-pokemon-generation-iii-event-compilation-savefiles/

**Comment by kamronbatman** [comment]
I have all of the GCEA pokemon. I just need to collate it, name them, and put them up.
As for JEREMY, we have _some_ of them, but not all of them.  I am still holding out for someone who might have them all in gen 3!

**Comment by fabiojc99** [comment]
Oh, nice. Thanks, I will be waiting for them to be put here then!

**Comment by kamronbatman** [comment]
Going to close this since GCEA is uploaded and Jeremy that we have is up.
