### ISSUE TITLE
Gen I Mew

### ISSUE THREAD

**Issue by fabiojc99** [projectpokemon/EventsGallery#77]
Gen I Mew has the wrong naming, it should be "RBY - YOSHIRB (55702) Mew (ENG)" instead of "RBY - YOSHIBB (55702) Mew (ENG)"

**Comment by kamronbatman** [comment]
Thank you!

**Comment by fabiojc99** [comment]
The name is till not right tho xD

**Comment by kamronbatman** [comment]
Oops! You are right!
