### ISSUE TITLE
Nobunaga's Shiny Rayquaza Game Version Serialization

### ISSUE THREAD

**Issue by crzyc** [projectpokemon/EventsGallery#87]
This file: 0059 BW - ノブナガ Shiny Rayquaza (JPN).pgf in Gen 5 can only be obtained by a BW cartridge, but the Wonder Card has no restriction on game version, making Nobunaga's Rayquaza having a BW2 origin also legal.

![PKHeX_2019-11-15_12-26-09](https://user-images.githubusercontent.com/18177787/68962673-1f097a80-07a3-11ea-9da5-4905c27f98a0.png)

![chrome_2019-11-15_12-23-44](https://user-images.githubusercontent.com/18177787/68962509-c6d27880-07a2-11ea-907a-52b085be1efe.png)

Source: [Serebii](https://www.serebii.net/events/dex/384.shtml).

Please close this issue if I am mistaken.

**Comment by kamronbatman** [comment]
The WC doesn't actually have the game origin restrictions in it. That was held in the original file on the distro ROM or the server.
Ref: https://projectpokemon.org/docs/gen-5/5th-generation-wondercard-map-r2/

We need to make a catalogue for PKHex to know this.
